-- ============================================================
-- BANKING DATA PLATFORM — ROLE BASED ACCESS CONTROL SETUP
-- Run this script as ACCOUNTADMIN when setting up a new env
-- ============================================================

-- Step 1: Create dedicated roles following least privilege
CREATE ROLE IF NOT EXISTS DBT_TRANSFORMER;   -- dbt service account
CREATE ROLE IF NOT EXISTS BANKING_ANALYST;   -- analytics team
CREATE ROLE IF NOT EXISTS BANKING_READER;    -- read-only business users

-- Step 2: Grant warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BANKING_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BANKING_READER;

-- Step 3: Grant database access
GRANT USAGE ON DATABASE BANKING_DW TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON DATABASE BANKING_DW TO ROLE BANKING_ANALYST;
GRANT USAGE ON DATABASE BANKING_DW TO ROLE BANKING_READER;

-- Step 4: DBT_TRANSFORMER — read RAW, write DBT_DEV
-- This is the only role dbt should run as in production
GRANT USAGE ON SCHEMA BANKING_DW.RAW TO ROLE DBT_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_DW.RAW TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE DBT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE DBT_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE DBT_TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE DBT_TRANSFORMER;

-- Step 5: BANKING_ANALYST — read all marts
GRANT USAGE ON SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE BANKING_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE BANKING_ANALYST;

-- Step 6: BANKING_READER — read only customer and transaction marts
-- Deliberately excluded: loan risk and fraud tables (sensitive data)
GRANT USAGE ON SCHEMA BANKING_DW.DBT_DEV_DBT_DEV TO ROLE BANKING_READER;
GRANT SELECT ON TABLE BANKING_DW.DBT_DEV_DBT_DEV.MART_CUSTOMER_360 TO ROLE BANKING_READER;
GRANT SELECT ON TABLE BANKING_DW.DBT_DEV_DBT_DEV.MART_TRANSACTION_ANALYTICS TO ROLE BANKING_READER;

-- Step 7: Assign roles to users
-- Replace AKSHAYDUBEY401 with your dbt service account user
GRANT ROLE DBT_TRANSFORMER TO USER AKSHAYDUBEY401;

-- ============================================================
-- ROLE SUMMARY
-- DBT_TRANSFORMER : dbt service account — RAW read, DEV write
-- BANKING_ANALYST : analytics team — all marts read
-- BANKING_READER  : business users — customer + txn only
-- ACCOUNTADMIN    : admin only — never used for dbt runs
-- ============================================================